<?php
/**
 *
 * Markup CKEditor
 *
 * @author Robin Sallis
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class InputfieldMarkupCKEditor extends InputfieldMarkup {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Markup CKEditor',
			'summary' => 'Inputfield for displaying markup editable via CKEditor. For use with Form Builder module.',
			'version' => '0.1.1',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/InputfieldMarkupCKEditor',
			'icon' => 'wpforms',
		);
	}

	/**
	 * Method called right before Inputfield markup is rendered
	 *
	 * @param Inputfield|InputfieldWrapper|null $parent
	 * @param bool $renderValueMode
	 * @return bool
	 *
	 */
	public function renderReady(Inputfield $parent = null, $renderValueMode = false) {
		// Set skipLabel if the noLabel option is checked
		if($this->noLabel) $this->skipLabel = Inputfield::skipLabelHeader;
		return parent::renderReady($parent, $renderValueMode);
	}

	/**
	 * Config inputfields
	 */
	public function ___getConfigInputfields() {

		// Get InputfieldMarkup config fields
		$inputfields = parent::___getConfigInputfields();

		// Remove the original markup text field
		$inputfields->remove('markupText');

		// Get textformatters field
		$textformatters = $inputfields->getChildByName('textformatters');

		// Add new CKEditor markup text field before textformatters field
		$f = $this->modules->get('InputfieldCKEditor');
		$f_name = 'markupText';
		$f->name = $f_name;
		$f->id = $f_name;
		$f->label = $this->_('Markup Text');
		$f->rows = 10;
		$f->value = $this->$f_name;
		$f->toolbar = str_replace('PWImage, ', '', $f->toolbar);
		$inputfields->insertBefore($f, $textformatters);

		// Checkbox field for option to hide inputfield label
		$f = $this->modules->get('InputfieldCheckbox');
		$f_name = 'noLabel';
		$f->name = $f_name;
		$f->label = $this->_("Hide inputfield label in form");
		$f->checked = $this->$f_name === 1 ? 'checked' : '';
		$inputfields->insertBefore($f, $textformatters);

		return $inputfields;
	}
	
}
